version: '3'
services:
  database:
    image: postgres:10.10
  worker_queue:
    image: redis:4.0.14
  object_storage:
    image: minio/minio:RELEASE.2019-12-19T22-52-26Z
    environment:
      MINIO_ACCESS_KEY: abcdef123
      MINIO_SECRET_KEY: abcdef123
    command: server /data
    ports:
      - 9000:9000
  worker:
    image: spree
    restart: always
    environment:
      SECRET_KEY_BASE: meh
      DATABASE_URL: postgres://postgres@database/spree
      BUCKETEER_AWS_ACCESS_KEY_ID: abcdef123
      BUCKETEER_AWS_SECRET_ACCESS_KEY: abcdef123
      BUCKETEER_BUCKET_NAME: spree
      BUCKETEER_AWS_REGION: us-east-1
      S3_ENDPOINT: http://object_storage:9000
      REDIS_URL: redis://worker_queue:6379
    command: sidekiq -C config/sidekiq.yml
  web:
    image: spree
    restart: always
    environment:
      SECRET_KEY_BASE: meh
      DATABASE_URL: postgres://postgres@database/spree
      BUCKETEER_AWS_ACCESS_KEY_ID: abcdef123
      BUCKETEER_AWS_SECRET_ACCESS_KEY: abcdef123
      BUCKETEER_BUCKET_NAME: spree
      BUCKETEER_AWS_REGION: us-east-1
      S3_ENDPOINT: http://object_storage:9000
      REDIS_URL: redis://worker_queue:6379
      SIDEKIQ_USERNAME: admin
      SIDEKIQ_PASSWORD: password
    command: rails s
    ports:
      - 3000:3000
